# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - imagesearchpokemon

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://pokeregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_747e2d8f005c4317907b6d11760ec5d0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_03ae32b0751a487d9e48b9e2ebcdc4a8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: pokeregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_747e2d8f005c4317907b6d11760ec5d0 }}/poke-image:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'imagesearchpokemon'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9a904f4d331846ebaa6573068d3a5dc9 }}
        images: 'pokeregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_747e2d8f005c4317907b6d11760ec5d0 }}/poke-image:${{ github.sha }}'